[alias]
minimal = "run --no-default-features"
mails = "run --features mails"
otel = "run --features otel"
reports = "run --features reports"
mails-otel = "run --features mails,otel"
full = "run --features full"
