[alias]
minimal = "run --no-default-features"
mails = "run --no-default-features --features mails"
otel = "run --no-default-features --features otel"
reports = "run --no-default-features --features reports"
mails-otel = "run --no-default-features --features mails,otel"
full = "run --no-default-features --features full"
