name: Release
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Install Rust toolchain
        run: rustup update stable && rustup default stable
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v6
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            semantic-release-cargo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
